ci rebase

diff --git a/.sourcecraft/ci.yaml b/.sourcecraft/ci.yaml
--- a/.sourcecraft/ci.yaml
+++ b/.sourcecraft/ci.yaml
@@ -23,104 +23,104 @@ workflows:
                 git push origin --tags --force
   
 
-  create_rebase_branch:
-    inputs:
-        target_branch:
-          description: 'Branch for rebasing (e.g. yc/master)'
-          required: true
-          default: 'yc/master'
-          type: string
-        upstream_tag:
-          description: 'Upstream tag to rebase onto (e.g. v25.12.5.6-stable)'
-          required: true
-          type: string
+  # create_rebase_branch:
+  #   inputs:
+  #       target_branch:
+  #         description: 'Branch for rebasing (e.g. yc/master)'
+  #         required: true
+  #         default: 'yc/master'
+  #         type: string
+  #       upstream_tag:
+  #         description: 'Upstream tag to rebase onto (e.g. v25.12.5.6-stable)'
+  #         required: true
+  #         type: string
 
-    tasks:
-      - name: create-candidate
-        cubes:
-          - name: configure-git
-            script:
-              - |
-                set -ex
-                git config --global user.name 'CI Bot'
-                git config --global user.email 'cibot@example.com'
-          - name: validation-upstream-tag
-            script:
-              - |
-                if ! git rev-parse "${{ inputs.upstream_tag }}" >/dev/null 2>&1; then
-                  echo "::error::Tag ${{ inputs.upstream_tag }} not found in upstream."
-                  exit 1
-                fi
-          - name: detect-old-base
-            script:
-              - |
-                OLD_BASE=$(git describe --tags --abbrev=0 --match "v*" HEAD)
-                echo "Current base determined as: $OLD_BASE"
+  #   tasks:
+  #     - name: create-candidate
+  #       cubes:
+  #         - name: configure-git
+  #           script:
+  #             - |
+  #               set -ex
+  #               git config --global user.name 'CI Bot'
+  #               git config --global user.email 'cibot@example.com'
+  #         - name: validation-upstream-tag
+  #           script:
+  #             - |
+  #               if ! git rev-parse "${{ inputs.upstream_tag }}" >/dev/null 2>&1; then
+  #                 echo "::error::Tag ${{ inputs.upstream_tag }} not found in upstream."
+  #                 exit 1
+  #               fi
+  #         - name: detect-old-base
+  #           script:
+  #             - |
+  #               OLD_BASE=$(git describe --tags --abbrev=0 --match "v*" HEAD)
+  #               echo "Current base determined as: $OLD_BASE"
 
-                # Is already rebased
-                if [ "$OLD_BASE" == "${{ inputs.upstream_tag }}" ]; then
-                  echo "::error::Branch is already based on ${{ inputs.upstream_tag }}."
-                  exit 1
-                fi
+  #               # Is already rebased
+  #               if [ "$OLD_BASE" == "${{ inputs.upstream_tag }}" ]; then
+  #                 echo "::error::Branch is already based on ${{ inputs.upstream_tag }}."
+  #                 exit 1
+  #               fi
 
-                # Is new tag ancestor of old base
-                if git merge-base --is-ancestor "${{ inputs.upstream_tag }}" HEAD; then
-                  echo "::warning::Tag ${{ inputs.upstream_tag }} is already merged into history."
-                  exit 1
-                fi
+  #               # Is new tag ancestor of old base
+  #               if git merge-base --is-ancestor "${{ inputs.upstream_tag }}" HEAD; then
+  #                 echo "::warning::Tag ${{ inputs.upstream_tag }} is already merged into history."
+  #                 exit 1
+  #               fi
 
-                echo "old_base=$OLD_BASE" >> $SOURCECRAFT_ENV
+  #               echo "old_base=$OLD_BASE" >> $SOURCECRAFT_ENV
 
-          - name: create-and-checkout-rebase-branch
-            script:
-              - |
-                SAFE_TAG=$(echo "${{ inputs.upstream_tag }}" | sed 's/[^a-zA-Z0-9.-]//g')
-                SAFE_TARGET=$(echo "${{ inputs.target_branch }}" | sed 's/\//-/g')
+  #         - name: create-and-checkout-rebase-branch
+  #           script:
+  #             - |
+  #               SAFE_TAG=$(echo "${{ inputs.upstream_tag }}" | sed 's/[^a-zA-Z0-9.-]//g')
+  #               SAFE_TARGET=$(echo "${{ inputs.target_branch }}" | sed 's/\//-/g')
 
-                CANDIDATE_NAME="rebase/${SAFE_TARGET}/${SAFE_TAG}"
-                echo "candidate_name=$CANDIDATE_NAME" >> $SOURCECRAFT_ENV
+  #               CANDIDATE_NAME="rebase/${SAFE_TARGET}/${SAFE_TAG}"
+  #               echo "candidate_name=$CANDIDATE_NAME" >> $SOURCECRAFT_ENV
 
-                git checkout -b $CANDIDATE_NAME          
-          - name: do-rebase
-            script:
-              - |                
-                $OLD_BASE=$old_base
-                $NEW_BASE="${{ inputs.upstream_tag }}"
+  #               git checkout -b $CANDIDATE_NAME          
+  #         - name: do-rebase
+  #           script:
+  #             - |                
+  #               $OLD_BASE=$old_base
+  #               $NEW_BASE="${{ inputs.upstream_tag }}"
 
-                if git rebase --onto $NEW_BASE $OLD_BASE HEAD; then
-                  echo "Rebase is done successfully."
-                else
-                  echo "::error::Rebase is failed due to conflicts."
-                  echo "::notice::Manual intervention required. Please rebase locally."
-                  git rebase --abort
-                  exit 1
-                fi
-          - name: reset-yc-version
-            script:
-              - |
-                NEW_VERSION="${{ inputs.upstream_tag }}-yc.1"
-                echo "Setting internal version to: $NEW_VERSION"
+  #               if git rebase --onto $NEW_BASE $OLD_BASE HEAD; then
+  #                 echo "Rebase is done successfully."
+  #               else
+  #                 echo "::error::Rebase is failed due to conflicts."
+  #                 echo "::notice::Manual intervention required. Please rebase locally."
+  #                 git rebase --abort
+  #                 exit 1
+  #               fi
+  #         - name: reset-yc-version
+  #           script:
+  #             - |
+  #               NEW_VERSION="${{ inputs.upstream_tag }}-yc.1"
+  #               echo "Setting internal version to: $NEW_VERSION"
 
-                echo "$NEW_VERSION" > version_yc.txt
-                git add version_yc.txt
-                # --allow-empty just in case if version was not updated
-                git commit -m "Build: Reset version to $NEW_VERSION after rebase" --allow-empty
-          - name: push-rebase-branch
-            script:
-                - git push origin $candidate_name --force
-          - name: create-rebase-pr
-            script:
-              - |
-                curl -X POST \
-                  -H "Authorization: Bearer $SOURCECRAFT_TOKEN" \
-                  -H "Content-Type: application/json" \
-                  -d '{
-                    "source": ${candidate_name},
-                    "target": "${{ inputs.target_branch }}"},
-                    "title": "Rebase ${{ inputs.target_branch }} on ${{ inputs.upstream_tag }}",
-                    "description": "Rebase PR description"
-                  }' \
-                  "https://public-api.o.cloud.yandex.net/repos/yc/clickhouse/pull-requests"
+  #               echo "$NEW_VERSION" > version_yc.txt
+  #               git add version_yc.txt
+  #               # --allow-empty just in case if version was not updated
+  #               git commit -m "Build: Reset version to $NEW_VERSION after rebase" --allow-empty
+  #         - name: push-rebase-branch
+  #           script:
+  #               - git push origin $candidate_name --force
+  #         - name: create-rebase-pr
+  #           script:
+  #             - |
+  #               curl -X POST \
+  #                 -H "Authorization: Bearer $SOURCECRAFT_TOKEN" \
+  #                 -H "Content-Type: application/json" \
+  #                 -d '{
+  #                   "source": ${candidate_name},
+  #                   "target": "${{ inputs.target_branch }}"},
+  #                   "title": "Rebase ${{ inputs.target_branch }} on ${{ inputs.upstream_tag }}",
+  #                   "description": "Rebase PR description"
+  #                 }' \
+  #                 "https://public-api.o.cloud.yandex.net/repos/yc/clickhouse/pull-requests"
 
 
 
